name: "Armbian/build"
author: "Stefan Dej"
description: "Build armbian images"
inputs:
  configfile:
    description: "Config file name"
    required: true

runs:
  using: "composite"
  steps:
    #- name: Runner prepare
    #  uses: ./actions/runner-prepare
    - name: Free Github Runner
      uses: descriptinc/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Read configs
      id: config
      shell: bash
      run: |
        source ./build-configs/configs/config-default.conf
        source ./build-configs/configs/${{ inputs.configfile }}.conf

        echo "armbian_repository=${ARMBIAN_REPOSITORY}" >> $GITHUB_OUTPUT
        echo "armbian_branch=${ARMBIAN_BRANCH}" >> $GITHUB_OUTPUT

    - name: Checkout armbian Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        repository: ${{ steps.config.outputs.armbian_repository }}
        ref: ${{ steps.config.outputs.armbian_branch }}
        path: build

    - name: Create config-default.conf
      shell: bash
      run: |
        mkdir -p ./build/userpatches
        cp ./build-configs/configs/config-default.conf ./build/userpatches/config-settings.conf
        cat ./build-configs/configs/${{ inputs.configfile }}.conf >> ./build/userpatches/config-settings.conf
        echo "::group::Output config-settings.conf"
        cat ./build/userpatches/config-settings.conf
        echo "::endgroup::"

    - name: Add custom board configuration
      shell: bash
      run: |
        if [[ -d ./build-configs/boards ]]; then
          cp -R -v ./build-configs/boards/* ./build/config/boards
        else
          echo -e "\e[0;33mNo custom board configuration found ... [SKIPPED]\e[0m"
          exit 0
        fi

    - name: Add custom userpatches
      shell: bash
      run: |
        if [[ -d ./build-configs/userpatches ]]; then
          cp -R -v ./build-configs/userpatches/* ./build/userpatches
        else
          echo -e "\e[0;33mNo custom userpatches found ... [SKIPPED]\e[0m"
          exit 0
        fi

    - name: sed VERSION
      shell: bash
      run: |
        sed -i 's/-trunk//' ./build/VERSION
        echo "::group::Output VERSION"
        cat ./build/VERSION
        echo "::endgroup::"

    - name: Build Image
      shell: bash
      run: |
        cd ./build
        ./compile.sh settings

    - name: Fix userrights
      shell: bash
      run: |
        sudo chown -R $USER:$USER ${{ github.workspace }}/build || true
        sudo chmod 0777 -R ${{ github.workspace }}/build || true
        echo "::group::List files"
        ls -l ${{ github.workspace }}/build
        echo "::endgroup::"
